
name: Provision EC2 Instances with terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Ec2-Provision:
    runs-on: ubuntu-latest
    container:
      image: node:18
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: check node version
        run: node --version
        
      - name: Check Python Version
        run: python --version

      - name: Check AWS CLI Version
        run: aws --version
        
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
