
name: Provision EC2 Instances with terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Ec2-Provision:
    runs-on: ubuntu-latest
    container:
      image: node:18
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: check node version
        run: node --version
        
